/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Unkn0wn0ne_rootmyvalet_RootHandler */

#ifndef _Included_com_Unkn0wn0ne_rootmyvalet_RootHandler
#define _Included_com_Unkn0wn0ne_rootmyvalet_RootHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Unkn0wn0ne_rootmyvalet_RootHandler
 * Method:    runExploit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_Unkn0wn0ne_rootmyvalet_RootHandler_runExploit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
